### ISSUE TITLE
Memory functions

### ISSUE THREAD

**Issue by EdmundKorley** [emkk/libft#1]
Implement a group of functions that manipulate raw memory. We should optimize the order in which we are going to write these.
- [x] memset
- [x] bzero
- [x] memcpy
- [x] memccpy
- [x] memmove
- [x] memchr
- [x] memrchr 🌟
- [x] memcmp
- [x] memalloc 🌱
- [x] memdel 🌱

🌟 - non-mandatory, "bonus".
🌱 - not available or exposed by the C standard library.

**Comment by EdmundKorley** [comment]
A 42 fellow's [unit test case](https://github.com/alelievr/libft-unit-test/blob/master/src/test_functions.c#L796) has a very indirect way of saying `ft_memmove` shouldn't `malloc`, but I think calling `malloc` for the temporary buffer is conceptually cleaner for now.

Also: need to research what it means to _protect_ a function in C.

**Comment by hlpostman** [comment]
Huh. Thanks.

**Comment by EdmundKorley** [comment]
Just linking to the [conversation](https://github.com/alelievr/libft-unit-test/issues/3) on the unit test repo that shows using or not using `malloc` in `ft_memmove` is optional albeit it is a critical memory optimization to **not** allocate memory on a system with low  resources.

**Comment by hlpostman** [comment]
https://social.msdn.microsoft.com/Forums/en-US/a07dfe33-d4a7-4c8d-bf62-d934d6b616d0/memcpy-memmove-or-custom-methods-is-faster?forum=vcgeneral
